name: "Setup and install"
description: "Set up Bun, typstyle, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: "Set up Bun"
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: "package.json" # or ".tool-versions" or ".bun-version"

    - name: "Set up cargo-binstall"
      uses: cargo-bins/cargo-binstall@main

    - name: "Install typstyle"
      shell: bash
      run: cargo-binstall typstyle --no-confirm

    - name: "Install dependencies"
      shell: bash
      run: bun install
